できてないけど一旦アップ
f-hasubo/ICA_practice pull request #1
Opened 2022-04-23 04:51 UTC by r-kisimoto

僕は間違ってない…間違ってないんだぁ!!!!!!!!!!!!!!!

2022-04-23 06:17 UTC, f-hasubo requested changes

2022-04-23 06:17 UTC, f-hasubo commented on ICA.m
> +        E = R/T;
ここTで割ってるけど，このTの値は離散インデスクのtだね．それなので，これは秒数のtではないですね...

2022-04-23 06:17 UTC, f-hasubo commented on ICA.m
> +        fai = y./(sigma*abs(y)); % スコア関数(ラプラス分布)
faiに欠損値が入っている!?どうにか処理したい

2022-04-23 08:25 UTC, f-hasubo commented on ICA.m
> +        E = R/T;
ごめん，説明めちゃめちゃ悪かった．．
ICAの資料の9行目のところでRをTで割ってると思うんだけど，そのTの値はxの信号の離散時間分なので，今回だと160000になります．
ただ，岸本くんが作ってくれたこのプログラムのコードの23行目のTは10となってるはずです．なぜなら7行目でサンプリング周波数で割っているから．．
そこの修正は必要かもです〜！！

2022-04-23 10:35 UTC, f-hasubo commented on ICA.m
> +for t = 0:deltaTime:T-deltaTime
この部分もforループ使わずに，分離信号yを求めることができるよ〜〜．
単純な行列積で！！

2022-04-23 10:36 UTC, f-hasubo commented on ICA.m
> +end
この部分もforループ使わずに，分離信号yを求めることができるよ〜〜．
単純な行列積で！！

2022-04-23 10:38 UTC, f-hasubo commented on ICA.m
> +end
これらを修正できたら，プロジェクションバック法しようか！！単純に，分離行列の逆行列をかけるだけだけど，ちょっとyの信号を工夫しないといけない．詳しくはICAの資料見てやろうか！

2022-04-24 04:48 UTC, f-hasubo commented on ICA.m
>          R = fai*y.';
欠損値処理は，fillmissing関数を使って実装しよう．（謎に欠損値が入ってしまっている...）
0で割っているのが原因そう...だから，欠損値部分は0で埋めてみようか！

2022-04-24 04:50 UTC, f-hasubo commented on ICA.m
> +        E = R/time;
今，timeという変数に信号長(10)の値が入っているよね．．．でも，ここは「サンプリング周波数*信号長」の値を使わないといけないよ〜
つまり，今，信号のサンプリング周波数16kHz，信号長10なので，160000を使って，Eを求めてみようか！

2022-04-24 04:51 UTC, f-hasubo commented on ICA.m
> +        E = R/time;
むむむ，このtimeは10が入っているから，まずそうだね．．
ICAの資料にあるtの範囲は[1~T]となっていて，このTの値はサンプリング周波数で信号をサンプリングしたときのインデックスの値になるから，Tの値は「サンプリング周波数*時間」になるね．．
そのため，timeは10だけど，ここはTで割り算をしないといけない．つまり「サンプリング周波数*時間」で割る．
今回だと，サンプリング周波数16kHz，信号長10秒なので，Tの値は160000だね...EはRから160000を割った値にしよう〜！

2022-04-24 07:55 UTC, f-hasubo commented
良いのではないでしょうか！
個人的にも，欠損値が出るのは違和感ありますが，おそらく0で割っている部分ですかね...また，確認してみてください！
というわけで，プロジェクションバック法の適用と，SDRの計算をしますか！
SDRはkitamura-labのリポジトリのbss_eval_sourcesを使うとできます．一応関数の中に，説明はあるのですが，わからないことあれば言ってください！
[SDRの計算プログラム（関数）](https://github.com/kitamura-laboratory/bssEvalHowTo/blob/main/bss_eval/bss_eval_sources.m)

2022-04-24 07:55 UTC, merged

2022-04-24 07:58 UTC, r-kisimoto commented
fillmissing関数を用いた結果L=8までは分離でき、９以降はWの各要素がinfになりました。そこでステップサイズが大きすぎて発散しているのかと考え、１０から0.5まで大幅に減らした結果L=30までうまくいきました。が、分離後の音声を聞いたところ、もとの音声と全く同じに感じます。ステップサイズを小さくしすぎたのが原因と考えていますが、蓮池さんの見解を伺いたいです。←これなら分離できてないに等しいし...
以前はステップサイズが10でもNaNもInfもなくうまくいったのに…てのは相変わらず疑問が残っていますが…

2022-04-24 08:08 UTC, f-hasubo commented
確かにステップサイズが大きすぎたのはありますね．．．
一旦僕の環境でも実装してみたいので，使用している音声だけ送ってもらえますか？？（女でかい.wavと男でかい.wav）